/*
 *
 *  * Copyright © 2016, Robosoft Technologies Pvt. Ltd
 *  * Written under contract by Robosoft Technologies Pvt. Ltd.
 *
 */

package com.air.movieapp.model;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;
import android.databinding.BaseObservable;
import android.databinding.Bindable;
import android.util.Log;

import com.air.movieapp.BR;

/**
 * Created by sagar on 20/8/16.
 */
@Entity
public class Movie extends BaseObservable{

    @PrimaryKey (autoGenerate = true)
    private int idAutoGenerated;

    //In title and overview @ColumnInfo is not written as member variable name should be the name of column
    private String title;

    @ColumnInfo(name = "releaseDate")
    private String release_date = "";

    private String overview;

    @ColumnInfo(name = "voteAverage")
    private float vote_average;

    private String type = "";

    private boolean visible = true;

    public Movie() {
    }

    public Movie(String title, String releaseDate, String overview, float voteAverage, String type) {
//        this.id = id;
        this.title = title;
        this.release_date = releaseDate;
        this.overview = overview;
        this.vote_average = voteAverage;
        this.type = type;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }


    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Bindable
    public boolean isVisible() {
        return visible;
    }

    public void setVisible(boolean visible) {
        this.visible = visible;
        notifyPropertyChanged(BR.visible);
    }

    /*    public String getReleaseDate() {
        return release_date;
    }

    public void setReleaseDate(String releaseDate) {
        this.release_date = releaseDate;
    }*/

    public String getOverview() {
        return overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }

/*    public float getVoteAverage() {
        return vote_average;
    }

    public void setVoteAverage(float voteAverage) {
        this.vote_average = voteAverage;
    }*/

    public int getIdAutoGenerated() {
        return idAutoGenerated;
    }

    public void setIdAutoGenerated(int idAutoGenerated) {
        this.idAutoGenerated = idAutoGenerated;
    }

    public String getRelease_date() {
        return release_date;
    }

    public void setRelease_date(String release_date) {
        this.release_date = release_date;
    }

    public float getVote_average() {
        return vote_average;
    }

    public void setVote_average(float vote_average) {
        this.vote_average = vote_average;
    }

    public void onClick(){
        Log.d("Movie", "onClick: " + "In Movie");
    }
}
